apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    name: frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP
  clusterIP: None
