apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    name: frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP
  clusterIP: None
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mqtt-service
# spec:
#   ports:
#   - name: mqtt
#     port: 1883
#     protocol: TCP
#     targetPort: mqtt
#   selector:
#     name: frontend
#   type: ClusterIP

