apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      name: frontend
  serviceName: frontend
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        name: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - frontend
            topologyKey: kubernetes.io/hostname
      containers:
      - name: gateway
        image: ghcr.io/keith-gamble/aks-lite-test/ignition-example:latest
        imagePullPolicy: Always
        imagePullSecrets:
        - name: github-registry-token
        resources:
          requests:
            memory: "1280Mi"
            cpu: "1"
        args:
        - --
        - gateway.useProxyForwardedHeader=true
        ports:
        - name: http
          containerPort: 8088
        envFrom:
        - secretRef:
            name: gateway-base-config
        readinessProbe:
          exec:
            command:
            - health-check.sh
            - -t
            - "3"
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 10
          timeoutSeconds: 3
