apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: example-aks-hosted

patches:
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: example.kgamble.dev
    - op: add
      path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
      value: redirect-to-https@file
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: frontend


# Patch teh secretGenerator to set the correct namespace
secretGenerator:
- name: gateway-base-secrets
  behavior: merge
  literals:
  - gateway-base-config=gateway-base-config
  namespace: example-aks-lite
