apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: example-aks-hosted

patches:
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: example.kgamble.dev

  target:
    group: networking.k8s.io
    kind: Ingress
    name: frontend
    version: v1


    # - op: add
    # path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
    # value: redirect-to-https@file
