apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-application
  namespace: argocd
spec:
  project: example-project
  source:
    repoURL: 'https://github.com/keith-gamble/aks-lite-test.git'
    targetRevision: HEAD
    path: k8s/overlays/aks
  destination:
    name: 'in-cluster' # This is used when ArgoCD is running in the same cluster as the application
    namespace: example-aks-hosted
    server: ''
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
